listen: "0.0.0.0:9030"
mysql: "root:123456@tcp(127.0.0.1:3306)/iac?charset=utf8mb4&parseTime=True&loc=Local"
consul:
  address: "10.0.2.135:8900"
  id: "Iac-Portal"
  ip: "192.168.1.197"
  port: 9030
  tags: "region:DC1;someKey:someValue"
  interval: "5s"
  timeout: "3s"
  deregister_after: "30s"
task:
  time_ticker: 10
  log_path: "."
gitlab:
  url: "http://gitlab.idcos.com/"
  token: "yFBZ6epTKWx9zDGBBLbg"
  username: "xiaohei"
log:
  log_level: "debug"
  log_max_days: 7
