version: "3"
services:
  iac-portal:
    container_name: iac-portal
    image: "${DOCKER_REGISTRY}cloudiac:${VERSION}"
    command: ["sh", "-c", "./iac-portal -c config-portal.yml"]
    ports:
      - "9030:9030"
    volumes:
      - .env:/usr/yunji/cloudiac/.env:ro
      - config-portal.yaml:/usr/yunji/cloudiac/config-portal.yaml:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always

  ct-runner:
    container_name: ct-runner
    image: "${DOCKER_REGISTRY}cloudiac:${VERSION}"
    command: [ "sh", "-c", "./ct-runner -c config-runner.yml" ]
    ports:
      - "19030:19030"
    volumes:
      - config-runner.yml:/usr/yunji/cloudiac/config-runner.yaml:ro
      - provider:/usr/yunji/cloudiac/provider:rw
    environment:
      - TZ=Asia/Shanghai
    restart: always
