- name: "Create {{WORKDIR}}/var/"
  file:
    path: "{{WORKDIR}}/var"
    state: directory

- name: Download iac package
  get_url:
    url: "{{iac_package_url}}"
    dest: "{{WORKDIR}}"
  register: iac_package
  when: "'://' in iac_package_url"

- name: Copy iac package
  copy:
    src: "{{iac_package_url}}"
    dest: "{{WORKDIR}}"
  register: iac_package
  when: "'://' not in iac_package_url"

- name: Extract iac package
  command: "tar -xf {{iac_package.dest}} -C {{WORKDIR}}"
  when: iac_package.changed
  notify: Restart iac-portal

- name: Download iac-repos package
  get_url:
    url: "{{iac_repos_package_url}}"
    dest: "{{WORKDIR}}"
  register: iac_repos_package
  when: "'://' in iac_repos_package_url"

- name: Copy iac-repos package
  copy:
    src: "{{iac_repos_package_url}}"
    dest: "{{WORKDIR}}"
  register: iac_repos_package
  when: "'://' not in iac_repos_package_url"

- name: Extract iac-repos package
  command: "tar -xf {{iac_repos_package.dest}} -C {{WORKDIR}}"
  when: iac_repos_package.changed

- name: Copy config-portal.yml
  copy:
    src: "{{WORKDIR}}/config-portal.yml.sample"
    dest: "{{WORKDIR}}/config-portal.yml"
    force: no
    remote_src: yes
  notify: Restart iac-portal

- name: Copy .env
  copy:
    src: "{{WORKDIR}}/dotenv.sample"
    dest: "{{WORKDIR}}/.env"
    force: no
    remote_src: yes

- name: Config .env
  blockinfile:
    dest: "{{WORKDIR}}/.env"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (IAC PORTAL)"
    block: |
      IAC_ADMIN_EMAIL={{admin_email}}
      IAC_ADMIN_PASSWORD={{admin_password}}
      MYSQL_DATABASE={{mysql_db}}
      MYSQL_HOST={{mysql_host}}
      MYSQL_USER={{mysql_user}}
      MYSQL_PASSWORD={{mysql_password}}
      PORTAL_ADDRESS={{portal_address}}
      CONSUL_ADDR={{consul_address}}
      SERVICE_IP={{ansible_default_ipv4.address}}
      SERVICE_ID={{portal_service_id}}
      SERVICE_TAGS={{portal_service_tags}}
  notify: Restart iac-portal

- name: Install iac-portal service
  become: yes
  copy:
    src: "{{WORKDIR}}/iac-portal.service"
    dest: /etc/systemd/system/
    remote_src: yes

- name: Start iac-portal
  service:
    name: iac-portal
    state: started
    enabled: yes
  when: not iac_package.changed
